version: '3'
services:
  cache_centos8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-8
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: el8
    command: make rpm
  cache_centos7:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-7
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: el7
    command: make rpm
  cache_centos6:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.centos-6
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: el6
    command: make rpm
  cache_ubuntu16:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-16
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: xenial
    command: make deb
  cache_ubuntu18:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-18
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: bionic
    command: make deb
  cache_ubuntu20:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ubuntu-20
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: focal
    command: make deb
  cache_debian8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-8
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: jessie
    command: make deb
  cache_debian9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-9
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: stretch
    command: make deb
  cache_debian11:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.debian-11
      args:
        GO_VERSION: 1.14.4
    volumes:
      - .:/go/src/github.com/STNS/cache-stnsd
      - ~/pkg:/go/pkg
      - ~/src:/go/src
    environment:
      DIST: bullseye
    command: make deb
